//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Methodica_Exams.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class methodicadbEntities : DbContext
    {
        public methodicadbEntities()
            : base("name=methodicadbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<alumnos> alumnos { get; set; }
        public virtual DbSet<apartados> apartados { get; set; }
        public virtual DbSet<cursos> cursos { get; set; }
        public virtual DbSet<examenes> examenes { get; set; }
        public virtual DbSet<ficheros> ficheros { get; set; }
        public virtual DbSet<notas> notas { get; set; }
        public virtual DbSet<preguntas> preguntas { get; set; }
        public virtual DbSet<profesores> profesores { get; set; }
        public virtual DbSet<respuestas> respuestas { get; set; }
        public virtual DbSet<temas> temas { get; set; }
        public virtual DbSet<usuarios> usuarios { get; set; }
    }
}
